import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

val generatedBuildInfo = layout.buildDirectory.dir("generated/sources/buildInfo/kotlin")
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val outputDirectory = generatedBuildInfo
    val embeddedVersion = project.version.toString()
    inputs.property("version", embeddedVersion)
    outputs.dir(outputDirectory)
    doLast {
        val output = outputDirectory.get().file("de/samthedev/veloutils/proxy/bootstrap/BuildInfo.kt").asFile
        output.parentFile.mkdirs()
        output.writeText(
            """// Generated by Gradle. Do not edit.
                |package de.samthedev.veloutils.proxy.bootstrap
                |
                |public object BuildInfo {
                |    public const val VERSION: String = "$embeddedVersion"
                |}
                |""".trimMargin(),
        )
    }
}

kotlin.sourceSets.named("main") { kotlin.srcDir(generateBuildInfo) }

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    id("com.gradleup.shadow")
}

dependencies {
    implementation(project(":veloutils-api"))
    implementation(project(":veloutils-common"))
    implementation(project(":veloutils-protocol"))
    compileOnly("com.velocitypowered:velocity-api:4.1.0-SNAPSHOT")
    implementation("org.spongepowered:configurate-yaml:4.2.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.xerial:sqlite-jdbc:3.50.3.0")
    implementation("com.mysql:mysql-connector-j:9.4.0")
    implementation("org.postgresql:postgresql:42.7.7")
    testImplementation("net.kyori:adventure-text-minimessage:4.24.0")
}

tasks.jar { enabled = false }

tasks.processResources {
    val projectVersion = project.version.toString()
    inputs.property("version", projectVersion)
    filesMatching("velocity-plugin.json") { expand("version" to projectVersion) }
}

tasks.named<ShadowJar>("shadowJar") {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    archiveBaseName.set("veloutils-proxy")
    archiveClassifier.set("")
    mergeServiceFiles()
    exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
    exclude("META-INF/LICENSE", "META-INF/LICENSE.txt", "META-INF/NOTICE", "META-INF/NOTICE.txt")
    relocate("org.spongepowered.configurate", "de.samthedev.veloutils.lib.configurate")
    relocate("com.zaxxer.hikari", "de.samthedev.veloutils.lib.hikari")
    relocate("kotlinx", "de.samthedev.veloutils.lib.kotlinx")
}

tasks.assemble { dependsOn(tasks.shadowJar) }
